name: Lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    name: Lint the repository
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Poetry
      run: pipx install poetry
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: poetry
    - uses: actions/cache@v4
      id: cache-poetry
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
    - name: Install Dependencies
      if: steps.cache-poetry.outputs.cache-hit != 'true'
      run: |
        poetry install --with dev
    - name: Run Mypy
      run: |
        poetry run mypy .
    - name: Run Ruff
      run: |
        poetry run ruff .